// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjclktpuipxrvhxvhfsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqY2xrdHB1aXB4cnZoeHZoZnNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTM0ODQsImV4cCI6MjA2OTM2OTQ4NH0.nVaO0ltK0aCYy53gY9RtcfVTYOB-eJV2OTUrEJdc36A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});